# Generated by Django 4.2.7 on 2023-12-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=30)),
                ('dosage', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
